api/v1/clinic/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<pk>[\d]+)$', views.ClinicView.as_view()),
    url(r'^(?P<pk>[\d]+)/test/$', views.TestView.as_view()),
    url(r'^(?P<pk>[\d]+)/review/$', views.ClinicReviewView.as_view()),
]

api/v1/doctor/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<pk>[\d]+)$', views.DoctorView.as_view()),
    url(r'^$', views.DoctorListView.as_view()),
    url(r'^(?P<pk>[\d]+)/clinic/$', views.DoctorClinicView.as_view()),
    url(r'^(?P<pk>[\d]+)/patients/$', views.DoctorPatientListView.as_view()),
    url(r'^(?P<pk>[\d]+)/appointment/$', views.DoctorAppointmentView.as_view()),
    url(r'^(?P<pk>[\d]+)/appointment/history$', views.DoctorAppointmentHistoryView.as_view()),
    url(r'^(?P<pk>[\d]+)/appointment/visit$', views.DoctorAppointmentVisitView.as_view()),
    url(r'^(?P<pk>[\d]+)/appointment/(?P<appointment_id>[\d]+)/status/$', views.DoctorStatusView.as_view()),
    url(r'^(?P<pk>[\d]+)/clinic/(?P<clinic_id>[\d]+)/appointment_slots/$', views.DoctorAppointmentSlotView.as_view()),
    url(r'^(?P<pk>[\d]+)/visit/$', views.DoctorVisitView.as_view()),
    url(r'^(?P<pk>[\d]+)/review/$', views.DoctorReviewView.as_view()),
]

portal/urls.py
from django.conf.urls import url

from portal import views

urlpatterns = [
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^home$', views.PortalHomeView.as_view(), name='home'),
    url(r'^profile$', views.ProfileView.as_view(), name='profile'),
    url(r'^clinics$', views.ClinicsView.as_view(), name='clinics'),
    url(r'^clinic/(?P<pk>[\d]+)/$', views.ClinicView.as_view(), name='clinic_detail'),
    url(r'^doctor_setting/clinic/(?P<clinic_id>[\d]+)/$', views.DoctorSettingView.as_view(), name='doctor_setting'),
    url(r'^doctor/(?P<pk>[\d]+)/key_factors$', views.DoctorKeyFactorsView.as_view(), name='doctor_key_factors'),
    url(r'^doctor/(?P<pk>[\d]+)/stats', views.DoctorStatsView.as_view(), name='doctor_stats'),
    url(r'^doctor/operations$', views.DoctorOperationsView.as_view(), name='doctor_operations'),
    url(r'^patients$', views.PatientsView.as_view(), name='patients'),
    url(r'^doctors$', views.DoctorsView.as_view(), name='doctors'),
    url(r'^announcements$', views.AnnouncementsView.as_view(), name='announcements'),
]

quicklic_backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from quicklic_backend.settings import STATIC_ROOT, MEDIA_ROOT
from website import urls as website_urls
from portal import urls as portal_urls
from api.v1 import urls as v1_urls
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(website_urls, namespace="website")),
    url(r'^portal/', include(portal_urls, namespace="portal")),
    url(r'^api/v1/', include(v1_urls)),
]

urlpatterns += [
    url(r'^static/(.*)$', serve, {'document_root': STATIC_ROOT, 'show_indexes': True}),
    url(r'^media/(.*)$', serve, {'document_root': MEDIA_ROOT, 'show_indexes': True})
]

entities/clinic/forms.py
from django import forms
from .models import Clinic


class ClinicForm(forms.ModelForm):
    class Meta:
        model = Clinic
        fields = [
            'code', 'name', 'phone', 'email', 'website', 'location', 'city', 'country',
            'is_lab', 'is_active', 'rating', 'image'
        ]

portal/forms.py
from django import forms

from entities.person.models import User, DoctorHoliday


class LoginForm(forms.Form):
    phone = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class DoctorHolidayForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(DoctorHolidayForm, self).__init__(*args, **kwargs)
        self.fields['notes'].required = False
        self.fields['day'].input_formats = ['%d-%m-%Y']

    class Meta:
        model = DoctorHoliday
        fields = ['physician', 'day', 'notes']

api/v1/clinic/views.py
from rest_framework.generics import RetrieveAPIView, ListAPIView
from entities.clinic.models import Clinic
from entities.test_menu.models import Test
from libs.authentication import UserAuthentication
from api.v1.serializers import ClinicSerializer, TestSerializer, ReviewSerializer
from libs.custom_exceptions import ClinicDoesNotExistsException
from libs.permission import PatientDoctorPermission
from libs.utils import get_start_datetime_from_date_string, get_end_datetime_from_date_string


class ClinicView(RetrieveAPIView):
    """
    View for getting Clinic.

    **Example requests**:

        GET /clinic/{id}
    """

    authentication_classes = (UserAuthentication,)
    serializer_class = ClinicSerializer
    queryset = Clinic.objects.all()


class TestView(ListAPIView):
    """
    View for listing clinic's tests.

    **Example requests**:
        GET /clinic/{id}/test/
    """

    authentication_classes = (UserAuthentication,)
    permission_classes = (PatientDoctorPermission,)
    serializer_class = TestSerializer

    def get_queryset(self):
        return Test.objects.filter(is_active=True, clinic_id=self.kwargs['pk']).order_by('id')


class ClinicReviewView(ListAPIView):
    """
    View for getting clinic reviews

    **Example requests**:

        GET /clinic/{id}/review/

        **filters**
            doctor_id: Filter with clinic
            start_date: time filter
            end_date: time filter
    """

    authentication_classes = (UserAuthentication,)
    serializer_class = ReviewSerializer

    def get_queryset(self):
        try:
            clinic = Clinic.objects.get(pk=int(self.kwargs['pk']))
            reviews = clinic.reviews.all().order_by('created_at')

            if 'doctor_id' in self.request.query_params:
                reviews = reviews.filter(doctor=self.request.query_params.get('doctor_id'))

            if 'start_date' in self.request.query_params:
                start_datetime = get_start_datetime_from_date_string(self.request.query_params.get('start_date'))
                reviews = reviews.filter(created_at__gte=start_datetime)

            if 'end_date' in self.request.query_params:
                end_datetime = get_end_datetime_from_date_string(self.request.query_params.get('end_date'))
                reviews = reviews.filter(created_at__lte=end_datetime)

            return reviews
        except Clinic.DoesNotExist:
            raise ClinicDoesNotExistsException()

api/v1/doctor/views.py
import pytz
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.generics import RetrieveUpdateAPIView, ListAPIView
from rest_framework.response import Response
from rest_framework.views import APIView
from django.db.models import Q
from datetime import datetime, timedelta

from entities.notification.models import Notification
from entities.appointment.models import Appointment, Visit
from entities.person.models import Doctor, Patient, DoctorHoliday
from libs.authentication import UserAuthentication
from libs.custom_exceptions import InvalidInputDataException, InvalidAppointmentStatusException, \
    DoctorDoesNotExistsException, InvalidDateTimeException
from libs.permission import (
    DoctorOwnerPermission,
    AppointmentOwnerPermission,
    PatientDoctorPermission,
    PatientBelongsDoctorPermission,
)
from libs.utils import str2bool, get_datetime_from_date_string, get_date_from_date_string, \
    get_datetime_range_from_date_string, get_interval_between_time, get_start_datetime_from_date_string, \
    get_end_datetime_from_date_string, get_datetime_now_by_date
from api.v1.serializers import DoctorSerializer, ClinicSerializer, AppointmentSerializer, VisitSerializer, \
    ReviewSerializer, PatientSerializer

User = get_user_model()


class DoctorView(RetrieveUpdateAPIView):
    """
    View for creating and getting doctor.

    **Example requests**:

        GET /doctor/{id}
        PUT /doctor/{id}
        PATCH /doctor/{id}
    """
    authentication_classes = (UserAuthentication,)
    permission_classes = (DoctorOwnerPermission,)
    serializer_class = DoctorSerializer
    queryset = Doctor.objects.all()


class DoctorListView(ListAPIView):
    """
    View for getting all doctors.

    **Example requests**:

        GET /doctor/

    **filters**:
        - active=true: Only active doctors
        - clinic_id=1
        - country_id=1
        - city_id=1
        - specialization_id=1
        - services_ids=1,2,3
        - query=aamish
    """

    authentication_classes = (UserAuthentication,)
    serializer_class = DoctorSerializer
    queryset = Doctor.objects.all().order_by('id')

    def get_queryset(self):
        doctors = Doctor.objects.all().order_by('id')

        if 'clinic_id' in self.request.query_params:
            doctors = doctors.filter(clinic=self.request.query_params.get('clinic_id', None))

        if 'country_id' in self.request.query_params:
            doctors = doctors.filter(country_id=self.request.query_params.get('country_id'))

        if 'city_id' in self.request.query_params:
            doctors = doctors.filter(city_id=self.request.query_params.get('city_id'))

        if 'specialization_id' in self.request.query_params:
            doctors = doctors.filter(specialization_id=self.request.query_params.get('specialization_id'))

        if 'services_ids' in self.request.query_params:
            service_ids = [int(id) for id in self.request.query_params.get('services_ids').split(',')]
            doctors = doctors.filter(services__in=service_ids)

        if 'query' in self.request.query_params:
            doctors = doctors.filter(Q(first_name__icontains=self.request.query_params.get('query')) | Q(last_name__icontains=self.request.query_params.get('query')))

        doctors = doctors.filter(is_active=str2bool(self.request.query_params.get('active', 'true')))

        return doctors


class DoctorPatientListView(ListAPIView):
    """
    View for getting all patients.

    **Example requests**:

        GET /doctor/{doctor_id}/patients
    """

    authentication_classes = (UserAuthentication,)
    serializer_class = PatientSerializer
    queryset = Patient.objects.all().order_by('first_name')

    def get_queryset(self):
        clinic_ids = self.request.user.doctor.clinic.all().values_list("id", flat=True)
        patients = Patient.objects.filter(clinic__id__in=clinic_ids, is_active=True).order_by('first_name')
        return patients


class DoctorClinicView(ListAPIView):
    """
    View for getting doctor's clinics.

    **Example requests**:

        GET /doctor/{id}/clinic/
    """

    authentication_classes = (UserAuthentication,)
    permission_classes = (DoctorOwnerPermission,)
    serializer_class = ClinicSerializer

    def get_queryset(self):
        return self.request.user.clinic.all().order_by('id')


class DoctorAppointmentView(ListAPIView):
    """
    View for getting doctor's appointments

    **Example requests**:

        GET /doctor/{id}/appointments/

    **filters**:
        - start_date
        - end_date
        - status=1
        - clinic_id=1
        - reason_id=1
    """

    authentication_classes = (UserAuthentication,)
    permission_classes = (DoctorOwnerPermission,)
    serializer_class = AppointmentSerializer

    def get_queryset(self):
        appointments = self.request.user.doctor.appointments.all().order_by('start_datetime')

        if 'start_date' in self.request.query_params:
            start_datetime = get_start_datetime_from_date_string(self.request.query_params.get("start_date"))
            appointments = appointments.filter(start_datetime__gte=start_datetime)

        if 'end_date' in self.request.query_params:
            end_datetime = get_end_datetime_from_date_string(self.request.query_params.get("end_date"))
            appointments = appointments.filter(end_datetime__lte=end_datetime)

        if 'status' in self.request.query_params:
            statuses = [int(id) for id in self.request.query_params.get('status').split(',')]
            appointments = appointments.filter(status__in=statuses)

        if 'clinic_id' in self.request.query_params:
            appointments = appointments.filter(clinic_id=self.request.query_params.get('clinic_id'))

        if 'reason_id' in self.request.query_params:
            appointments = appointments.filter(reason_id=self.request.query_params.get('reason_id'))

        return appointments


class DoctorAppointmentHistoryView(ListAPIView):
    """
    View for getting doctor's historic appointments

    **Example requests**:

        GET /doctor/{id}/appointments/history

    **filters**:
        - status=1
        - clinic_id=1
        - reason_id=1
    """

    authentication_classes = (UserAuthentication,)
    permission_classes = (DoctorOwnerPermission,)
    serializer_class = AppointmentSerializer

    def get_queryset(self):
        appointments = self.request.user.doctor.appointments.\
            filter(visit__isnull=False).order_by('-start_datetime')

        date_time_now = get_end_datetime_from_date_string(datetime.now().date())
        appointments = appointments.filter(start_datetime__lte=date_time_now)

        if 'status' in self.request.query_params:
            statuses = [int(id) for id in self.request.query_params.get('status').split(',')]
            appointments = appointments.filter(status__in=statuses)

        if 'clinic_id' in self.request.query_params:
            appointments = appointments.filter(clinic_id=self.request.query_params.get('clinic_id'))

        if 'reason_id' in self.request.query_params:
            appointments = appointments.filter(reason_id=self.request.query_params.get('reason_id'))

        return appointments


class DoctorAppointmentVisitView(ListAPIView):
    """
    View for getting doctor's appointments needed any action to be taken on

    **Example requests**:

        GET /doctor/{id}/appointments/visit

    **filters**:
        - start_date
        - end_date
        - status=1
        - clinic_id=1
        - reason_id=1
    """

    authentication_classes = (UserAuthentication,)
    permission_classes = (DoctorOwnerPermission,)
    serializer_class = AppointmentSerializer

    def get_queryset(self):
        statuses = [Appointment.Status.PENDING, Appointment.Status.CONFIRM]
        appointments = self.request.user.doctor.appointments.\
            filter(status__in=statuses, visit__isnull=True).order_by('-start_datetime')

        date_time_now = get_end_datetime_from_date_string(datetime.now().date())
        appointments = appointments.filter(start_datetime__lte=date_time_now)

        if 'status' in self.request.query_params:
            statuses = [int(id) for id in self.request.query_params.get('status').split(',')]
            appointments = appointments.filter(status__in=statuses)

        if 'clinic_id' in self.request.query_params:
            appointments = appointments.filter(clinic_id=self.request.query_params.get('clinic_id'))

        if 'reason_id' in self.request.query_params:
            appointments = appointments.filter(reason_id=self.request.query_params.get('reason_id'))

        return appointments


class DoctorStatusView(APIView):
    """
    View for changing appointment status

    **Example requests**:

        POST /doctor/{id}/appointment/{appointment_id}

        **params**
        status: int
    """

    authentication_classes = (UserAuthentication,)
    permission_classes = (DoctorOwnerPermission, AppointmentOwnerPermission)

    def post(self, request, pk, appointment_id):
        status_code = request.data.get('status', None)
        if status_code:
            if status_code in [Appointment.Status.CONFIRM, Appointment.Status.DISCARD, Appointment.Status.NOSHOW]:
                appointment = Appointment.objects.get(pk=appointment_id)
                appointment.status = status_code
                appointment.save()

                if status_code == Appointment.Status.CONFIRM:
                    heading = Notification.Message.APPOINTMENT_CONFIRMED["heading"]
                    content = Notification.Message.APPOINTMENT_CONFIRMED["contents"].format(
                        doctor=appointment.doctor.get_full_name())
                elif status_code == Appointment.Status.DISCARD:
                    heading = Notification.Message.APPOINTMENT_DISCARD["heading"]

templates/portal/announcements.html
{% extends "portal/base.html" %}
{% load static %}

{% block body_block %}
    <section id="content">
      <section class="vbox">
        <section class="scrollable padder">
          <div class="m-b-md">
            <div class="row">
              <div class="col-sm-6">
                <h3 class="m-b-none m-t-sm">Announcements</h3>
              </div>
            </div>
          </div>
          <div class="row">
              <div class="col-lg-12">
                  <form data-validate="parsley" action="{% url 'portal:announcements' %}" method="post">
                    {% csrf_token %}
                    <section class="panel panel-default">
                      <header class="panel-heading">
                        <span class="h4">Custom Announcements</span>
                      </header>
                      <div class="panel-body">
                        <p class="text-muted">Spread your words with our announcements feature!</p>
                          <label>Send to?</label>
                          <div class="form-group">
                            <div class="radio">
                              <label>
                                <input type="radio" name="send_to" id="1" value="1" checked>
                                All Patients of Related Clinics
                              </label>
                            </div>
                            {% if type == 3 %}
                                <div class="radio">
                                  <label>
                                    <input type="radio" name="send_to" id="2" value="2">
                                    All Doctors of Related Clinics
                                  </label>
                                </div>
                            {% endif %}
                          </div>
                          <div class="form-group">
                            <label>Message</label>
                            <textarea class="form-control" name="message" rows="6" data-minwords="6" data-required="true" placeholder="Type your message"></textarea>
                          </div>
                      </div>
                      <footer class="panel-footer text-right bg-light lter">
                        <button type="submit" class="btn btn-success btn-s-xs">Spread the word</button>
                      </footer>
                    </section>
                  </form>
                </div>
          </div>
        </section>
      </section>
    </section>
{% endblock %}

templates/portal/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    {% include 'portal/includes/header.html' %}
</head>

<body>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-dismissable alert-{{ message.tags }} my-alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <section class="vbox">
        {% include 'portal/includes/top_navbar.html' %}
        <section>
          <section class="hbox stretch">
            {% include 'portal/includes/navbar.html' %}
            <section id="content">
                {% block body_block %} {% endblock %}
              <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a>
            </section>
          </section>
        </section>
    </section>
    {% include 'portal/includes/footer_includes.html' %}
</body>
</html>

templates/portal/clinics.html
{% extends "portal/base.html" %}
{% load static %}

{% block body_block %}
    <section id="content">
      <section class="vbox">
        <section class="scrollable padder">
          <div class="m-b-md">
            <div class="row">
              <div class="col-sm-6">
                <h3 class="m-b-none m-t-sm"><b>Clinics</b></h3>
              </div>
            </div>
          </div>
          <div class="m-b-md">
            <div class="row">
              <div class="col-sm-6">
                <h3 class="m-b-none m-t-sm">{{ user.first_name }} {{ user.last_name }}</h3>
              </div>
              <div class="col-sm-6">
                <div class="text-right text-left-xs">
                  <div class="m-t-sm">
                    <span class="text-uc">{{ user.phone }}</span>
                    <div class="h4"><strong>
                        {% if type == 1 %}
                            Doctor
                        {% elif type == 3 %}
                            Admin
                        {% endif %}
                    </strong></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
                <section class="panel panel-default">
                    <header class="panel-heading">
                        <strong>My Clinics</strong>
                    </header>
                    <ul class="list-group alt">
                        {% for clinic in clinics %}
                            <li class="list-group-item">
                                <div class="media">
                                    <span class="pull-left thumb-sm">
                                        <img src="{{ clinic.image.url }}" alt="No Image" class="img-circle">
                                    </span>
                                    <div class="pull-right text-success m-t-sm">
                                        <a href="{% url 'portal:clinic_detail' clinic.id %}"> Details </a>
                                    </div>
                                    <div class="media-body">
                                        <div>
                                            <a>{{ clinic.name }}</a>
                                        </div>
                                        <small class="text-muted">Code: {{ clinic.code }}</small>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </section>
            </div>
          </div>
        </section>
      </section>
    </section>
{% endblock %}

templates/portal/doctor_operations.html
{% extends "portal/base.html" %}
{% load static %}

{% block body_block %}
    <section id="content">
      <section class="vbox">
        <section class="scrollable padder">
          <div class="m-b-md">
            <div class="row">
              <div class="col-sm-6">
                <h3 class="m-b-none m-t-sm">Holidays</h3>
              </div>
            </div>
          </div>
          <div class="m-b-md">
            <div class="row">
              <div class="col-sm-6">
                <h3 class="m-b-none m-t-sm">{{ user.first_name }} {{ user.last_name }}</h3>
              </div>
              <div class="col-sm-6">
                <div class="text-right text-left-xs">
                  <div class="m-t-sm">
                    <span class="text-uc">{{ user.phone }}</span>
                    <div class="h4"><strong>Doctor</strong></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <form class="form-horizontal" data-validate="parsley" action="{% url 'portal:doctor_operations' %}" method="post">
              {% csrf_token %}
                <section class="panel panel-default">
                  <header class="panel-heading">
                    <strong>Mark a Holiday</strong>
                  </header>
                  <div class="panel-body">
                    <p>
                        <small>Allow doctors to mark a future holiday.</small>
                    </p>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Holiday</label>
                        <div class="col-sm-10">
                            <input class="input-sm input-s datepicker-input form-control" name="day" size="16" type="text" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy">
                        </div>
                    </div>
                    <p>
                        <small>All future appointments of the day will be discarded. Notification to all patients will be sent so that they can create a new one with you.</small>
                    </p>
                  </div>
                    <footer class="panel-footer text-right bg-light lter">
                    <button type="submit" class="btn btn-success btn-s-xs">Submit</button>
                  </footer>
                </section>
              </form>
            </div>
            <div class="col-lg-6">
              <section class="panel panel-default">
                  <header class="panel-heading">
                    <strong>Upcoming Holidays</strong>
                  </header>
              </section>
              <section class="comment-list block">
                  {% if holidays|length > 0 %}
                    {% for holiday in holidays %}
                      <article class="comment-item">
                      <span class="arrow left"></span>
                      <section class="comment-body panel panel-default">
                        <header class="panel-heading bg-white">
                          <a>Holiday on {{ holiday.day }}</a>
                        </header>
                        <div class="panel-body">
                            {% if holiday.note|length > 0 %}
                                <div>{{ holiday.note }}</div>
                            {% else %}
                                <div>No note found for this.</div>
                            {% endif %}
                        </div>
                      </section>
                    </article>
                    {% endfor %}
                  {% else %}
                    <p>No Holiday for Future</p>
                  {% endif %}
              </section>
                  <!-- / .comment-list -->
            </div>
          </div>
        </section>
      </section>
    </section>
{% endblock %}

templates/portal/doctors.html
{% extends "portal/base.html" %}
{% load static %}

{% block body_block %}
    <section id="content">
      <section class="vbox">
        <section class="scrollable padder">
          <div class="m-b-md">
            <div class="row">
              <div class="col-sm-6">
                <h3 class="m-b-none m-t-sm">Doctors</h3>
              </div>
            </div>
          </div>
          <div class="row">
            <section class="panel panel-default">
                <header class="panel-heading">
                  All Related Doctors of the Clinics
                </header>
                <div class="table-responsive">
                  <table class="table table-striped b-t b-light">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Clinic</th>
                        <th>Address</th>
                        <th>Statistics</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for doctor in doctors %}
                          <tr>
                            <td>{{ doctor.get_full_name }}</td>
                            <td>{{ doctor.phone }}</td>
                            <td>{{ doctor.clinic_names }}</td>
                            <td>{{ doctor.formatted_address }}</td>
                            <td>
                                <a href="{% url 'portal:doctor_key_factors' doctor.id %}" class="btn btn-xs btn-info">Key Factors</a>
                                <a href="{% url 'portal:doctor_stats' doctor.id %}" class="btn btn-xs btn-info">Statistics</a>
                            </td>
                          </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                </div>
                <footer class="panel-footer">
                </footer>
              </section>
          </div>
        </section>
      </section>
    </section>
{% endblock %}

templates/portal/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% include 'portal/includes/header.html' %}
    <body>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-dismissable alert-{{ message.tags }}">
                    <a href="#" class="closebtn" data-dismiss="alert" aria-label="close">&times;</a>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <section id="content" class="m-t-lg wrapper-md animated fadeInUp">
            <div class="container aside-xxl">
                <img class="portal-logo" src="{% static 'website/images/logo-light.png' %}">
              <section class="panel panel-default bg-white m-t-lg">
                <header class="panel-heading text-center">
                  <strong>Sign in</strong>
                </header>
                <form class="panel-body wrapper-lg" action="{% url 'portal:login' %}" method="post" >
                    {% csrf_token %}
                      <div class="form-group">
                        <label class="control-label">Phone</label>
                        <input type="text" placeholder="+920001234567" name="phone" class="form-control input-lg">
                      </div>
                      <div class="form-group">
                        <label class="control-label">Password</label>
                        <input type="password" id="inputPassword" name="password" placeholder="Password" class="form-control input-lg">
                      </div>
                      <button type="submit" class="btn btn-primary">Sign in</button>
                      <div class="line line-dashed"></div>
                        Don't have an account? Learn More!
                      <a href="{% url 'website:home' %}" class="btn btn-default btn-block">Contact Us</a>
                    </form>
                  </section>
                </div>
        </section>
        {% include 'portal/includes/footer_includes.html' %}
    </body>
</html>