portal/urls.py
from django.conf.urls import url

from portal import views

urlpatterns = [
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^home$', views.PortalHomeView.as_view(), name='home'),
    url(r'^profile$', views.ProfileView.as_view(), name='profile'),
    url(r'^clinics$', views.ClinicsView.as_view(), name='clinics'),
    url(r'^clinic/(?P<pk>[\d]+)/$', views.ClinicView.as_view(), name='clinic_detail'),
    url(r'^doctor_setting/clinic/(?P<clinic_id>[\d]+)/$', views.DoctorSettingView.as_view(), name='doctor_setting'),
    url(r'^doctor/(?P<pk>[\d]+)/key_factors$', views.DoctorKeyFactorsView.as_view(), name='doctor_key_factors'),
    url(r'^doctor/(?P<pk>[\d]+)/stats', views.DoctorStatsView.as_view(), name='doctor_stats'),
    url(r'^doctor/operations$', views.DoctorOperationsView.as_view(), name='doctor_operations'),
    url(r'^patients$', views.PatientsView.as_view(), name='patients'),
    url(r'^doctors$', views.DoctorsView.as_view(), name='doctors'),
    url(r'^announcements$', views.AnnouncementsView.as_view(), name='announcements'),
]

quicklic_backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from quicklic_backend.settings import STATIC_ROOT, MEDIA_ROOT
from website import urls as website_urls
from portal import urls as portal_urls
from api.v1 import urls as v1_urls
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(website_urls, namespace="website")),
    url(r'^portal/', include(portal_urls, namespace="portal")),
    url(r'^api/v1/', include(v1_urls)),
]

urlpatterns += [
    url(r'^static/(.*)$', serve, {'document_root': STATIC_ROOT, 'show_indexes': True}),
    url(r'^media/(.*)$', serve, {'document_root': MEDIA_ROOT, 'show_indexes': True})
]

portal/forms.py
from django import forms

from entities.person.models import User, DoctorHoliday


class LoginForm(forms.Form):
    phone = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class DoctorHolidayForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(DoctorHolidayForm, self).__init__(*args, **kwargs)
        self.fields['notes'].required = False
        self.fields['day'].input_formats = ['%d-%m-%Y']

    class Meta:
        model = DoctorHoliday
        fields = ['physician', 'day', 'notes']

portal/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http.response import HttpResponseRedirect
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.views.generic.base import View
from rest_framework.views import APIView

from entities.clinic.models import Clinic
from entities.person.models import Doctor
from portal import constants
from portal.forms import LoginForm, ProfileForm, DoctorHolidayForm
from portal.statistics_helper import get_doctor_appointment_stats, get_admin_appointment_stats, \
    get_key_factors_for_doctor, get_doctor_future_holidays, get_patients_for_doctor, get_patients_for_admin, \
    send_announcement_to_all_patients, send_announcement_to_all_doctors, get_doctors_for_admin

User = get_user_model()


class LoginView(TemplateView):
    template_name = "portal/login.html"

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        return context

    @transaction.atomic
    def post(self, request):
        form = LoginForm(request.POST)

        if form.is_valid():
            user = authenticate(
                phone=form.cleaned_data["phone"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                if hasattr(user, 'moderator') or hasattr(user, 'doctor'):
                    if user.is_active:
                        login(request, user)
                    else:
                        messages.error(request, constants.UserIsNotActive)
                        return HttpResponseRedirect(reverse('portal:login'))
                else:
                    messages.error(request, constants.UserNotAllowed)
                    return HttpResponseRedirect(reverse('portal:login'))
            else:
                messages.error(request, constants.UserIsNotAuthenticated)
                return HttpResponseRedirect(reverse('portal:login'))
        else:
            messages.error(request, constants.OPERATION_UNSUCCESSFUL)
            return HttpResponseRedirect(reverse('portal:login'))
        return HttpResponseRedirect(reverse('portal:home'))


class LogoutView(View):
    def get(self, request, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('portal:login'))


class PortalHomeView(TemplateView):
    template_name = "portal/home.html"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseRedirect(reverse('portal:login'))

        return super(PortalHomeView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(PortalHomeView, self).get_context_data(**kwargs)
        if self.request.user.is_doctor():
            context['type'] = User.Role.DOCTOR
            context['user'] = self.request.user.doctor
            context['stats'] = get_doctor_appointment_stats(self.request.user.doctor)
        elif self.request.user.is_admin():
            context['type'] = User.Role.ADMIN
            context['user'] = self.request.user.moderator
            context['stats'] = get_admin_appointment_stats(self.request.user.moderator)
        return context


class ProfileView(TemplateView):
    template_name = "portal/profile.html"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseRedirect(reverse('portal:login'))

        return super(ProfileView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)

        if self.request.user.is_doctor():
            context['type'] = User.Role.DOCTOR
            context['user'] = self.request.user.doctor
        elif self.request.user.is_admin():
            context['type'] = User.Role.ADMIN
            context['user'] = self.request.user.moderator
        return context


class ClinicsView(TemplateView):
    template_name = "portal/clinics.html"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseRedirect(reverse('portal:login'))

        return super(ClinicsView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ClinicsView, self).get_context_data(**kwargs)

        if self.request.user.is_doctor():
            context['type'] = User.Role.DOCTOR
            context['user'] = self.request.user.doctor
        elif self.request.user.is_admin():
            context['type'] = User.Role.ADMIN
            context['user'] = self.request.user.moderator

        context['clinics'] = self.request.user.clinic.all()
        return context


class ClinicView(TemplateView):
    template_name = "portal/clinic.html"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseRedirect(reverse('portal:login'))

        clinic = Clinic.objects.filter(id=kwargs['pk']).first()
        if not clinic:
            return HttpResponseRedirect(reverse('portal:clinics'))

        return super(ClinicView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, pk, **kwargs):
        context = super(ClinicView, self).get_context_data(**kwargs)
        context['doctor_timings'] = None

        clinic = self.request.user.clinic.filter(id=pk).first()

        if self.request.user.is_doctor():
            context['type'] = User.Role.DOCTOR
            context['user'] = self.request.user.doctor

            clinic_setting = self.request.user.doctor.settings.filter(clinic=clinic).first()
            if clinic_setting:
                context['doctor_timings'] = clinic_setting.get_timings_with_switch()

        elif self.request.user.is_admin():
            context['type'] = User.Role.ADMIN
            context['user'] = self.request.user.moderator
        context['clinic'] = clinic

        return context


class DoctorSettingView(APIView):

    @transaction.atomic
    def post(self, request, clinic_id):
        data = request.POST
        setting = self.request.user.doctor.settings.filter(clinic_id=clinic_id).first()

        if not setting:
            messages.error(request, constants.OPERATION_UNSUCCESSFUL)
        else:
            previous_timings = setting.get_timings_with_switch()

            if "monday_check" in data:
                setting.monday_start = data['monday_start']
                setting.monday_end = data['monday_end']
            else:
                setting.monday_start = "00:00"
                setting.monday_end = "00:00"

            if "tuesday_check" in data:
                setting.tuesday_start = data['tuesday_start']
                setting.tuesday_end = data['tuesday_end']
            else:
                setting.tuesday_start = "00:00"
                setting.tuesday_end = "00:00"

            if "wednesday_check" in data:
                setting.wednesday_start = data['wednesday_start']
                setting.wednesday_end = data['wednesday_end']
            else:
                setting.wednesday_start = "00:00"
                setting.wednesday_end = "00:00"

            if "thursday_check" in data:
                setting.thursday_start = data['thursday_start']
                setting.thursday_end = data['thursday_end']
            else:
                setting.thursday_start = "00:00"
                setting.thursday_end = "00:00"

            if "friday_check" in data:
                setting.friday_start = data['friday_start']
                setting.friday_end = data['friday_end']
            else:
                setting.friday_start = "00:00"
                setting.friday_end = "00:00"

            if "saturday_check" in data:
                setting.saturday_start = data['saturday_start']
                setting.saturday_end = data['saturday_end']
            else:
                setting.saturday_start = "00:00"
                setting.saturday_end = "00:00"

            if "sunday_check" in data:
                setting.sunday_start = data['sunday_start']
                setting.sunday_end = data['sunday_end']
            else:
                setting.sunday_start = "00:00"
                setting.sunday_end = "00:00"

            setting.save()

            if previous_timings['monday']['start'] != setting.monday_start or previous_timings['monday']['end'] != setting.monday_end:
                self.request.user.doctor.cancel_appointment_due_to_time_changed(0)
            elif previous_timings['tuesday']['start'] != setting.tuesday_start or previous_timings['tuesday']['end'] != setting.tuesday_end:
                self.request.user.doctor.cancel_appointment_due_to_time_changed(1)
            elif previous_timings['wednesday']['start'] != setting.wednesday_start or previous_timings['wednesday']['end'] != setting.wednesday_end:
                self.request.user.doctor.cancel_appointment_due_to_time_changed(2)
            elif previous_timings['thursday']['start'] != setting.thursday_start or previous_timings['thursday']['end'] != setting.thursday_end:
                self.request.user.doctor.cancel_appointment_due_to_time_changed(3)
            elif previous_timings['friday']['start'] != setting.friday_start or previous_timings['friday']['end'] != setting.friday_end:
                self.request.user.doctor.cancel_appointment_due_to_time_changed(4)
            elif previous_timings['saturday']['start'] != setting.saturday_start or previous_timings['saturday']['end'] != setting.saturday_end:
                self.request.user.doctor.cancel_appointment_due_to_time_changed(5)

templates/portal/includes/footer.html
{% load static %}

<!-- start: FOOTER -->
<footer>
    <div class="footer-inner">
        <div class="pull-left">
            &copy; <span class="current-year"></span><span class="text-bold text-uppercase"> Quicklic</span>. <span>All rights reserved</span>
        </div>
        <div class="pull-right">
            <span class="go-top"><i class="ti-angle-up"></i></span>
        </div>
    </div>
</footer>
<!-- end: FOOTER -->

templates/portal/includes/footer_includes.html
{% load static %}

<script src="{% static 'portal/js/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'portal/js/bootstrap.js' %}"></script>
<!-- App -->
<script src="{% static 'portal/js/app.js' %}"></script>
<script src="{% static 'portal/js/app.plugin.js' %}"></script>
<script src="{% static 'portal/js/slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'portal/js/charts/easypiechart/jquery.easy-pie-chart.js' %}"></script>
<script src="{% static 'portal/js/charts/sparkline/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'portal/js/charts/flot/jquery.flot.min.js' %}"></script>
<script src="{% static 'portal/js/charts/flot/jquery.flot.tooltip.min.js' %}"></script>
<script src="{% static 'portal/js/charts/flot/jquery.flot.resize.js' %}"></script>
<script src="{% static 'portal/js/charts/flot/jquery.flot.grow.js' %}"></script>
<script src="{% static 'portal/js/charts/flot/demo.js' %}"></script>

<script src="{% static 'portal/js/calendar/bootstrap_calendar.js' %}"></script>
<script src="{% static 'portal/js/calendar/demo.js' %}"></script>

<script src="{% static 'portal/js/sortable/jquery.sortable.js' %}"></script>

<!-- fuelux -->
<script src="{% static 'portal/js/fuelux/fuelux.js' %}"></script>
<!-- datepicker -->
<script src="{% static 'portal/js/datepicker/bootstrap-datepicker.js' %}"></script>
<!-- slider -->
<script src="{% static 'portal/js/slider/bootstrap-slider.js' %}"></script>
<!-- file input -->
<script src="{% static 'portal/js/file-input/bootstrap-filestyle.min.js' %}"></script>
<!-- combodate -->
<script src="{% static 'portal/js/libs/moment.min.js' %}"></script>
<script src="{% static 'portal/js/combodate/combodate.js' %}"></script>
<!-- select2 -->
<script src="{% static 'portal/js/select2/select2.min.js' %}"></script>
<!-- wysiwyg -->
<script src="{% static 'portal/js/wysiwyg/jquery.hotkeys.js' %}"></script>
<script src="{% static 'portal/js/wysiwyg/bootstrap-wysiwyg.js' %}"></script>
<script src="{% static 'portal/js/wysiwyg/demo.js' %}"></script>

templates/portal/includes/header.html
{% load static %}

<meta charset="utf-8" />
  <title>Quicklic | Admin Portal</title>
  <meta name="description" content="Quicklic Doctor Patient" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'website/images/favicon.png' %}">
  <link rel="stylesheet" href="{% static 'portal/css/bootstrap.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'portal/css/animate.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'portal/css/font-awesome.min.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'portal/css/font.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'portal/js/calendar/bootstrap_calendar.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'portal/js/datepicker/datepicker.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'portal/css/app.css' %}" type="text/css" />
  <!--[if lt IE 9]>
    <script src="js/ie/html5shiv.js"></script>
    <script src="js/ie/respond.min.js"></script>
    <script src="js/ie/excanvas.js"></script>
  <![endif]-->

templates/portal/includes/navbar.html
<!-- .aside -->
<aside class="bg-light lter b-r aside-md hidden-print" id="nav">
  <section class="vbox">
    <header class="header bg-primary lter text-center clearfix">
        <p>Navigation</p>
    </header>
    <section class="w-f scrollable">
      <div class="slim-scroll" data-height="auto" data-disable-fade-out="true" data-distance="0" data-size="5px" data-color="#333333">

        <!-- nav -->
        <nav class="nav-primary hidden-xs">
          <ul class="nav">
            <li >
              <a href="{% url 'portal:home' %}"  >
                <i class="fa fa-home icon">
                  <b class="bg-nav-portal"></b>
                </i>
                <span>Home</span>
              </a>
            </li>
            <li >
              <a href="{% url 'portal:profile' %}"  >
                <i class="fa fa-user icon">
                  <b class="bg-nav-portal"></b>
                </i>
                <span>Profile</span>
              </a>
            </li>
            <li >
              <a href="{% url 'portal:clinics' %}"  >
                <i class="fa fa-hospital-o icon">
                  <b class="bg-nav-portal"></b>
                </i>
                <span>Clinics</span>
              </a>
            </li>
            <li >
              <a href="{% url 'portal:home' %}"  >
                <i class="fa fa-bar-chart-o icon">
                  <b class="bg-nav-portal"></b>
                </i>
                <span>Statistics</span>
              </a>
            </li>
            {% if type == 1 %}
                <li >
                  <a href="{% url 'portal:doctor_key_factors' user.id %}"  >
                    <i class="fa fa-key icon">
                      <b class="bg-nav-portal"></b>
                    </i>
                    <span>Key Factors</span>
                  </a>
                </li>
                <li >
                  <a href="{% url 'portal:doctor_operations'%}"  >
                    <i class="fa fa-gear icon">
                      <b class="bg-nav-portal"></b>
                    </i>
                    <span>Holidays</span>
                  </a>
                </li>
            {% elif type == 3 %}
                <li >
                  <a href="{% url 'portal:doctors'%}"  >
                    <i class="fa fa-group icon">
                      <b class="bg-nav-portal"></b>
                    </i>
                    <span>Doctors</span>
                  </a>
                </li>
            {% endif %}
            <li >
              <a href="{% url 'portal:patients' %}"  >
                <i class="fa fa-group icon">
                  <b class="bg-nav-portal"></b>
                </i>
                <span>Patients</span>
              </a>
            </li>
            <li >
              <a href="{% url 'portal:announcements' %}"  >
                <i class="fa fa-bullhorn icon">
                  <b class="bg-nav-portal"></b>
                </i>
                <span>Announcements</span>
              </a>
            </li>
          </ul>
        </nav>
        <!-- / nav -->
      </div>
    </section>
  </section>
</aside>
<!-- /.aside -->

templates/portal/includes/top_navbar.html
{% load static %}

<header class="bg-dark dk header navbar navbar-fixed-top-xs">
  <div class="navbar-header aside-md">
    <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen,open" data-target="#nav,html">
      <i class="fa fa-bars"></i>
    </a>
    <a href="#" class="navbar-brand" data-toggle="fullscreen"><img src="{% static 'portal/images/logo.png'%}" class="m-r-sm">Quicklic <b>Portal</b></a>
    <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".nav-user">
      <i class="fa fa-cog"></i>
    </a>
  </div>
  <ul class="nav navbar-nav navbar-right m-n hidden-xs nav-user">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span class="thumb-sm avatar pull-left">
            {% if user.avatar %}
                <img src="{{ user.avatar.url }}">
            {% else %}
                <img src="{% static "portal/images/avatar_default.jpg" %}">
            {% endif %}
        </span>
        {{ user.first_name }} <b class="caret"></b>
      </a>
      <ul class="dropdown-menu animated fadeInRight">
        <span class="arrow top"></span>
        <li>
          <a href="{% url "portal:logout" %}">Logout</a>
        </li>
      </ul>
    </li>
  </ul>
</header>