portal/urls.py
from django.conf.urls import url

from portal import views

urlpatterns = [
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^home$', views.PortalHomeView.as_view(), name='home'),
    url(r'^profile$', views.ProfileView.as_view(), name='profile'),
    url(r'^clinics$', views.ClinicsView.as_view(), name='clinics'),
    url(r'^clinic/(?P<pk>[\d]+)/$', views.ClinicView.as_view(), name='clinic_detail'),
    url(r'^doctor_setting/clinic/(?P<clinic_id>[\d]+)/$', views.DoctorSettingView.as_view(), name='doctor_setting'),
    url(r'^doctor/(?P<pk>[\d]+)/key_factors$', views.DoctorKeyFactorsView.as_view(), name='doctor_key_factors'),
    url(r'^doctor/(?P<pk>[\d]+)/stats', views.DoctorStatsView.as_view(), name='doctor_stats'),
    url(r'^doctor/operations$', views.DoctorOperationsView.as_view(), name='doctor_operations'),
    url(r'^patients$', views.PatientsView.as_view(), name='patients'),
    url(r'^doctors$', views.DoctorsView.as_view(), name='doctors'),
    url(r'^announcements$', views.AnnouncementsView.as_view(), name='announcements'),
]

quicklic_backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from quicklic_backend.settings import STATIC_ROOT, MEDIA_ROOT
from website import urls as website_urls
from portal import urls as portal_urls
from api.v1 import urls as v1_urls
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(website_urls, namespace="website")),
    url(r'^portal/', include(portal_urls, namespace="portal")),
    url(r'^api/v1/', include(v1_urls)),
]

urlpatterns += [
    url(r'^static/(.*)$', serve, {'document_root': STATIC_ROOT, 'show_indexes': True}),
    url(r'^media/(.*)$', serve, {'document_root': MEDIA_ROOT, 'show_indexes': True})
]

website/urls.py
from django.conf.urls import url, include

from website import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^contact_us$', views.ContactUsView.as_view(), name='contact-us'),
    url(r'^(?P<blog_id>\w+)/blog$', views.BlogView.as_view(), name='blog'),
    url(r'^blogs$', views.BlogListView.as_view(), name='blog-list'),
]

entities/blog/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Author(models.Model):
    name = models.CharField(_('name'), max_length=50, db_index=True)
    title = models.CharField(_('title'), max_length=255)
    image = models.ImageField(upload_to='uploads/authors/')
    facebook_url = models.CharField(_('facebook'), max_length=255)
    twitter_url = models.CharField(_('twitter'), max_length=255)
    instagram_url = models.CharField(_('instagram'), max_length=255)
    linkedin_url = models.CharField(_('linkedin'), max_length=255)
    is_active = models.BooleanField(default=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Blog(models.Model):
    author = models.ForeignKey(Author, related_name="author")
    title = models.CharField(_('title'), max_length=255)
    body = models.TextField(_('message'))
    image = models.ImageField(upload_to='uploads/blogs/')
    is_active = models.BooleanField(default=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

website/views.py
from django.http.response import HttpResponseRedirect
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse

from entities.blog.models import Blog
from website import constants
from website.forms import ContactForm
from django.contrib import messages


class HomeView(TemplateView):
    template_name = "website/main.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        # getting recent three blog posts
        blogs = Blog.objects.filter(is_active=True).order_by('-id')[:3]

        context['blogs'] = blogs
        return context


class ContactUsView(TemplateView):

    def post(self, request):
        form = ContactForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, constants.HELLO_MESSAGE)
            return HttpResponseRedirect(reverse('website:home'))

        messages.error(request, constants.OPERATION_UNSUCCESSFUL)
        return HttpResponseRedirect(reverse('website:home'))


class BlogView(TemplateView):
    template_name = "website/blog.html"

    def get_context_data(self, **kwargs):
        context = super(BlogView, self).get_context_data(**kwargs)

        blog_id = kwargs.get('blog_id', None)
        if blog_id:
            blog = Blog.objects.filter(id=blog_id).first()
            if blog:
                context['blog'] = blog
            else:
                messages.error(self.request, constants.OPERATION_UNSUCCESSFUL)
        else:
            messages.error(self.request, constants.OPERATION_UNSUCCESSFUL)
        return context


class BlogListView(TemplateView):
    template_name = "website/blog-list.html"

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)

        blogs = Blog.objects.filter(is_active=True).order_by('-id')
        context['blogs'] = blogs

        return context

templates/website/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    {% include 'website/includes/header.html' %}
</head>

<body>
    {% if messages %}
        {% for message in messages %}
            <div class="my-alert alert alert-dismissable alert-{{ message.tags }}">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block body_block %}{% endblock %}
    {% include 'website/includes/footer.html' %}
    {% include 'website/includes/footer_includes.html' %}
</body>
</html>

templates/website/blog-list.html
{% extends "website/base.html" %}
{% load static %}

{% block body_block %}
    {% include 'website/includes/blog_navbar.html' %}

    <section class="page-header colored">
        <div class="container">

            <div class="row flex">

                <div class="col-md-7 col-sm-7 col-xs-12">
                    <h2>Blog Posts</h2>
                </div>

            </div>

        </div>
    </section>

    <!-- Section blog standard -->
    <section class="blog-standard">
        <div class="container">

            <div class="row">

                <div class="col-md-8 col-sm-8 col-xs-12">

                    {% if blogs|length > 0 %}
                        {% for blog in blogs %}
                            <div class="blog-item">
                                <img src="{{ blog.image.url }}" alt="blog" />
                                <h2><a href="{% url 'website:blog' blog.id %}">{{ blog.title }}</a></h2>
                                <div class="meta">
                                    <span class="date">Posted on {{ blog.created_at }}</span>
                                </div>
                                <p>{{ blog.body|truncatechars:50 }}</p>
                                <a href="{% url 'website:blog' blog.id %}" class="btn btn-default">Read More</a>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>Ops! No Blog Posts Found.</p>
                    {% endif %}

                </div>

                <!-- sidebar -->
                <div class="col-md-4 col-sm-4 col-xs-12">


                </div>

            </div>

        </div>
    </section>

{% endblock %}

templates/website/blog.html
{% extends "website/base.html" %}
{% load static %}

{% block body_block %}
    {% include 'website/includes/blog_navbar.html' %}

    <section class="page-header colored">
        <div class="container">

            <div class="row flex">

                <div class="col-md-7 col-sm-7 col-xs-12">
                    <h2>{{ blog.title }}</h2>
                </div>

            </div>

        </div>
    </section>

    <section class="blog-standard">
        <div class="container">

            <div class="row">

                <div class="col-md-8 col-sm-8 col-xs-12">

                    <div class="blog-item">
                        <img src="{{ blog.image.url }}" alt="blog" />
                        <h2>{{ blog.title }}</h2>
                        <div class="meta">
                            <span class="date">Posted on {{ blog.created_at }}</span>
                        </div>
                        <p>
                            {{ blog.body | linebreaks}}
                        </p>
                        <ul class="social-icons">
                            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>

                </div>

                <div class="col-md-4 col-sm-4 col-xs-12">

                    <div class="widget about">

                        <h4 class="title">About Author</h4>
                        <img src="{{ blog.author.image.url }}" alt="author" />
                        <h3>{{ blog.author.name }}</h3>
                        <p>{{ blog.author.title }}</p>
                        <ul class="social-icons">
                            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>

                </div>

            </div>

        </div>
    </section>

{% endblock %}