portal/urls.py
from django.conf.urls import url

from portal import views

urlpatterns = [
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^home$', views.PortalHomeView.as_view(), name='home'),
    url(r'^profile$', views.ProfileView.as_view(), name='profile'),
    url(r'^clinics$', views.ClinicsView.as_view(), name='clinics'),
    url(r'^clinic/(?P<pk>[\d]+)/$', views.ClinicView.as_view(), name='clinic_detail'),
    url(r'^doctor_setting/clinic/(?P<clinic_id>[\d]+)/$', views.DoctorSettingView.as_view(), name='doctor_setting'),
    url(r'^doctor/(?P<pk>[\d]+)/key_factors$', views.DoctorKeyFactorsView.as_view(), name='doctor_key_factors'),
    url(r'^doctor/(?P<pk>[\d]+)/stats', views.DoctorStatsView.as_view(), name='doctor_stats'),
    url(r'^doctor/operations$', views.DoctorOperationsView.as_view(), name='doctor_operations'),
    url(r'^patients$', views.PatientsView.as_view(), name='patients'),
    url(r'^doctors$', views.DoctorsView.as_view(), name='doctors'),
    url(r'^announcements$', views.AnnouncementsView.as_view(), name='announcements'),
]

quicklic_backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from quicklic_backend.settings import STATIC_ROOT, MEDIA_ROOT
from website import urls as website_urls
from portal import urls as portal_urls
from api.v1 import urls as v1_urls
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(website_urls, namespace="website")),
    url(r'^portal/', include(portal_urls, namespace="portal")),
    url(r'^api/v1/', include(v1_urls)),
]

urlpatterns += [
    url(r'^static/(.*)$', serve, {'document_root': STATIC_ROOT, 'show_indexes': True}),
    url(r'^media/(.*)$', serve, {'document_root': MEDIA_ROOT, 'show_indexes': True})
]

website/urls.py
from django.conf.urls import url, include

from website import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^contact_us$', views.ContactUsView.as_view(), name='contact-us'),
    url(r'^(?P<blog_id>\w+)/blog$', views.BlogView.as_view(), name='blog'),
    url(r'^blogs$', views.BlogListView.as_view(), name='blog-list'),
]

website/views.py
from django.http.response import HttpResponseRedirect
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse

from entities.blog.models import Blog
from website import constants
from website.forms import ContactForm
from django.contrib import messages


class HomeView(TemplateView):
    template_name = "website/main.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        # getting recent three blog posts
        blogs = Blog.objects.filter(is_active=True).order_by('-id')[:3]

        context['blogs'] = blogs
        return context


class ContactUsView(TemplateView):

    def post(self, request):
        form = ContactForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, constants.HELLO_MESSAGE)
            return HttpResponseRedirect(reverse('website:home'))

        messages.error(request, constants.OPERATION_UNSUCCESSFUL)
        return HttpResponseRedirect(reverse('website:home'))


class BlogView(TemplateView):
    template_name = "website/blog.html"

    def get_context_data(self, **kwargs):
        context = super(BlogView, self).get_context_data(**kwargs)

        blog_id = kwargs.get('blog_id', None)
        if blog_id:
            blog = Blog.objects.filter(id=blog_id).first()
            if blog:
                context['blog'] = blog
            else:
                messages.error(self.request, constants.OPERATION_UNSUCCESSFUL)
        else:
            messages.error(self.request, constants.OPERATION_UNSUCCESSFUL)
        return context


class BlogListView(TemplateView):
    template_name = "website/blog-list.html"

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)

        blogs = Blog.objects.filter(is_active=True).order_by('-id')
        context['blogs'] = blogs

        return context

templates/website/includes/blog_navbar.html
<!-- Preloader -->
<div class="preloader-outer">
<div class="preloader" aria-busy="true" aria-label="Loading, please wait." role="progressbar"></div>
</div>

<!-- Navbar 1 -->
<nav class="navbar navbar-default navbar-static">
    <div class="container">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" class=
            "navbar-toggle collapsed" data-target="#navbar" data-toggle=
            "collapse" type="button"><span class="sr-only">Toggle
            navigation</span> <span class="icon-bar"></span> <span class=
            "icon-bar"></span> <span class="icon-bar"></span></button>
        </div>
        <div class="navbar-collapse collapse" id="navbar">

            <div class="navbar-right">

                <!-- Menu -->
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'website:home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'website:blog-list' %}">All Blogs</a>
                    </li>
                </ul>
                <!-- Menu end -->

                <ul class="nav navbar-nav social">
                    <li><a href="#" class="external"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#" class="external"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                </ul>

            </div>

        </div><!--/.nav-collapse -->
    </div>
</nav>
<!-- Navbar 1 end -->

templates/website/includes/footer.html
{% load static %}

<!-- Section footer 1 -->
<footer id="footer-1" class="footer">
    <div class="container">

        <!-- footer logo -->
        <img src="{% static 'website/images/logo-light.png' %}" class="footer-logo" alt="logo-footer" />

        <!-- copyright text -->
        <span class="copyright">© Copyright {% now "Y" %} Quicklic, All Rights Reserved. <br />Designed & Developed with passion and <i class="fa fa-heart" aria-hidden="true"></i> in Pakistan.</span>

        <!-- social icons -->
        <ul class="social-icons">
            <li><a href="https://www.facebook.com/quicklic/"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
        </ul>

    </div>
</footer>

templates/website/includes/footer_includes.html
{% load static %}

<!-- SCRIPTS -->
<script type="text/javascript" src="{% static 'website/js/jquery-1.12.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'website/js/jquery.easing.min.js' %}"></script>
<script type="text/javascript" src="{% static 'website/js/jquery.single-page.min.js' %}"></script>
<script type="text/javascript" src="{% static 'website/js/jquery.magnific-popup.min.js' %}"></script>
<script type="text/javascript" src="{% static 'website/bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'website/js/jquery.counterup.min.js' %}"></script>
<script type="text/javascript" src="{% static 'website/js/jquery.ajaxchimp.js' %}"></script>
<script type="text/javascript" src="{% static 'website/js/countdown.js' %}"></script>
<script type="text/javascript" src="{% static 'website/js/waypoints.min.js' %}"></script>
<script type="text/javascript" src="{% static 'website/js/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static 'website/js/scrollreveal.min.js' %}"></script>
<script type="text/javascript" src="{% static 'website/js/classie.js' %}"></script>
<script type="text/javascript" src="{% static 'website/js/custom.js' %}"></script>

<!-- Style Changer -->
<script type="text/javascript" src="{% static 'website/demo/style_switcher.js' %}"></script>

templates/website/includes/header.html
{% load static %}

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Quicklic</title>
<meta name="description" content="Quicklic">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'website/images/favicon.png' %}">

<!-- STYLESHEETS -->
<link rel="stylesheet" href="{% static 'website/bootstrap/css/bootstrap.min.css' %}" >
<link rel="stylesheet" href="{% static 'website/css/font-awesome.min.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'website/css/et-line.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'website/css/magnific-popup.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'website/css/slick.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'website/css/hover-min.css' %}" type="text/css" media="all">
<link rel="stylesheet" href="{% static 'website/css/style.css' %}" >

<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

templates/website/includes/navbar.html
{% load static %}

<!-- Preloader -->
<div class="preloader-outer">
    <div class="preloader" aria-busy="true" aria-label="Loading, please wait." role="progressbar"></div>
</div>

<!-- Navbar 2-1 -->
<nav class="navbar navbar-default navbar-light navbar-fixed-top top-nav">
    <div class="container">
        <div class="navbar-header flex">
            <button aria-controls="navbar" aria-expanded="false" class=
            "navbar-toggle collapsed" data-target="#navbar" data-toggle=
            "collapse" type="button"><span class="sr-only">Toggle
            navigation</span> <span class="icon-bar"></span> <span class=
            "icon-bar"></span> <span class="icon-bar"></span></button>

        </div>
        <div class="navbar-collapse collapse" id="navbar">

            <div class="navbar-right">

                <!-- Menu -->
                <ul id="slide-menu" class="nav navbar-nav">
                    <li>
                        <a href="#section-2-1">Home</a>
                    </li>
                    <li>
                        <a href="#section-2-3">Features</a>
                    </li>
                    <li>
                        <a href="#section-2-5">Screenshots</a>
                    </li>
                    <li>
                        <a href="#section-2-8">Team</a>
                    </li>
                    <li>
                        <a href="#section-2-11">Contact</a>
                    </li>
                    <li>
                        <a class="external" href="{% url 'website:blog-list' %}">Blog</a>
                    </li>
                </ul>
                <!-- Menu end -->

                <div class="nav navbar-nav navicon-wrap">
                    <span class="navicon"></span>
                </div>

                <ul class="nav navbar-nav social">
                    <li><a href="https://www.facebook.com/quicklic/" class="external"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                </ul>

            </div>

        </div><!--/.nav-collapse -->
    </div>
</nav>
<!-- Navbar 2-1 end -->